### ISSUE TITLE
Implement subsurfaces

### ISSUE THREAD

**Issue by Cloudef** [Cloudef/wlc#22]
We implement the interface, but it's actually stubbed.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by SirCmpwn** [comment]
Bump.

**Comment by ammen99** [comment]
This is also necessary for the new versions of Gedit and Nautilus(probably also others), where they use a subsurface for their menus.

**Comment by ammen99** [comment]
Anyway, could somebody give me a hint at what should be done to implement subsurfaces? I would like to try to implement them, but I'm not exactly sure what exactly must be done(e.g I suppose that the stubbed functions in compositor.c must be implemented and that when drawing a surface we must also draw its subsurfaces, but what more needs to be done - I have an initial *implementation* of these, but subsurfaces don't get focused, so I suspected something else must be done?)

**Comment by Cloudef** [comment]
@ammen99 First of all read the wayland protocol comments for subsurfaces closely.
I'm not sure about the details of focus with subsurfaces, but they should be in the explained in the comments. It may be the fact that wlc always focuses the view's main surface. 
If you are willing to work on it though, I suggest joining on the irc channel.

**Comment by ammen99** [comment]
Well, sorry for that, but I have no experience with IRC, so I can't join it. I resolved the problem with focusing subsurfaces, but now I want to ask a question - where would be the best place to render the subsurfaces of a surface. For now I just make a straightforward implementation in surface_paint_internal() in the GLES renderer, but obviously this shouldn't be the right place. My initial thoughts are to rework the function for rendering a view so that it uses the function for rendering surface which in turn would render the subsurfaces(all these functions are in render.c, i.e  backend independent). What are your thoughts on the matter?

**Comment by SirCmpwn** [comment]
>Well, sorry for that, but I have no experience with IRC, so I can't join it.

And you're unwilling to learn anything new?

**Comment by Cloudef** [comment]
@ammen99 You should render the subsurfaces in output.c, just like everything else. The stuff in gles2.c and render.c are low level functions.

You should really try get on irc though, #freenode is where you can find almost all of the FOSS project communication.
