### ISSUE TITLE
Add run loop hook

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#36]
wlc_interface.compositor.tick

**Comment by minus7** [comment]
Since wlc doesn't have it's own main loop, having a tick function seems kind of impossible. Might be better to just expose `wlc_event_loop` to the user and let them add timers, fd watcher, etc there.

**Comment by SirCmpwn** [comment]
How are animations usually implemented in compositors? Doing that through a timer seems like it would have several problems, over doing it in some sort of tick.

**Comment by minus7** [comment]
Animations do sound like something for a render hook indeed. There's the `wlc.signals.render` signal, which could become a point to hook into for that, but wlc signals API doesn't seem to be exposed.

**Comment by Cloudef** [comment]
There is already event-loop branch that exposes event-loop. Orbment will use this for 9p plugin. Wlc eventually exposes something for rendering and animation timings.

**Comment by Cloudef** [comment]
I merged the event loop branch. The animations and custom rendering needs more thinking. Especially rendering since I don't want to expose any primitive functions, and how you render depends on what renderer wlc uses (gles2 only currently). What I've planned in past is just to give render hooks for different scenarios (post-view render for example for view decorations) and the information what renderer wlc is using, if it's GLES2 you can just render using gles2 fine, not sure how this would be abstracted for possible pixman / drm renderers.
